[package]
name = "tobj"
version = "2.0.2"
authors = ["Will Usher <will@willusher.io>"]

description = "A lightweight OBJ loader in the spirit of tinyobjloader"
homepage = "https://github.com/Twinklebear/tobj"
documentation = "http://www.willusher.io/tobj/tobj/"
repository = "https://github.com/Twinklebear/tobj"
readme = "README.md"
keywords = ["obj", "wavefront", "graphics"]
license = "MIT"

exclude = [
	"*.obj",
	"*.mtl",
	".travis.yml",
]

[dependencies]
log = { version = "0.4.8", optional = true }
